using UnityEngine;
using System.Collections;

/// <summary>
/// Chunk is a 100 x 100 (To be changed later?) group of tiles housed in a managable
/// unit that is autogenerated as the rover explores more of the map. This is similar
/// to a chunk on Minecraft.
/// </summary>
public class Chunk {
	//Two dimensional array of tiles.
	private Tile[,] tileArray;
	// Coordinate of bottom left corner of chunk.
	private float xCoord;
	private float yCoord;
	//Index of Chunk in the array holding all chunks.
	private int xChunk;
	private int yChunk;


	//================================================================================
	/// <summary>
	/// Initializes a new instance of the <see cref="Chunk"/> class.
	/// The chunk knows it's bottom left coordinate.
	/// </summary>
	/// <param name="xCoord">X coordinate.</param>
	/// <param name="yCoord">Y coordinate.</param>
	public Chunk(float xCoord, float yCoord){
		this.xCoord = xCoord;
		this.yCoord = yCoord;

		return;
	}

	//================================================================================
	//Given a direction returns the index of the tiles adjacent to this one in that
	//direction.
	public int getAdjacentTiles(Direction direction,Tile currentTile){
		
		return -1;
		
	}
	// Update is called once per frame
	void Update () {
	
	}
	//================================================================================
}
