using UnityEngine;
using System.Collections;

/// <summary>
/// Chunk is a 100 x 100 (To be changed later?) group of tiles housed in a managable
/// unit that is autogenerated as the rover explores more of the map. This is similar
/// to a chunk on Minecraft.
/// </summary>
public class Chunk : Component{
	public string str = "Hello World!";
	//Two dimensional array of tiles.
	private Tile[,] tileArray;
	// Coordinate of bottom left corner of chunk.
	private float xCoord;
	private float yCoord;
	//Index of Chunk in the array holding all chunks.
	private int xChunk;
	private int yChunk;
	//GameObject containing child Tiles.
	private GameObject gameObject;

	//================================================================================
	/// <summary>
	/// Initializes a new instance of the <see cref="Chunk"/> class.
	/// The chunk knows it's bottom left coordinate.
	/// </summary>
	/// <param name="xCoord">X coordinate.</param>
	/// <param name="yCoord">Y coordinate.</param>
	public Chunk(float xCoord, float yCoord){
		float size = ChunkCreator.chunkSize;
		this.xCoord = xCoord;
		this.yCoord = yCoord;
		this.tileArray = new Tile[(int)size, (int)size];
		this.gameObject = new GameObject();

		//Add script to handle Hitbox of rover againts edges.
		//gameObject.AddComponent<ChunkExploration>();
		gameObject.name = "chunk";

	}
	public Tile[,] getTileArray(){
		return tileArray;

	}
	public GameObject getGameObject(){
		return gameObject;
		}
	//================================================================================
}
